baseURL = "https://aN0NyMoUs0000.github.io/"
# baseURL = "http://localhost:11038/"
languageCode = "en-us"
title = "MCQGen Demo"
theme = "PaperMod"

[params]
  customCSS = ["/css/mcq-style.css"] # Add custom CSS here
  showToc = false
  mode = "dark"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "MCQs"
    url = "/mcqs/"
    weight = 2
